services:
  opensearch:
    # NOTE: requires `sysctl -w vm.max_map_count=262144`
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=NdAiD123!qd
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"
    expose:
      - 9200
      - 9600
    mem_limit: 2147483648
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
  deepseek:
    build: ./deepseek
    image: llama-deepseek
    ports:
      - "11434:11434"
    expose:
      - 11434
    networks:
      - common
  embed:
    build: ./embed
    image: test-embed
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - common
  reranker:
    build: ./reranker
    image: test-reranker
    ports:
      - "8001:8001"
    expose:
      - 8001
    networks:
      - common
  qdrant:
    image: qdrant/qdrant:v1.13.6
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    networks:
      - common
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./.qdrant_data:/qdrant/storage
  doc_storage:
    image: postgres:16.8
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - ./.postgres_data:/data/postgres
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - common
    restart: unless-stopped

networks:
  common:
    driver: bridge

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  opensearch-data:
    driver: local