CREATE TABLE document(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  doc text
);

CREATE TABLE document_segment(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fragment text,
  start_pos integer not null,
  end_pos integer not null,
  qdrant_id varchar(255) not null,
  document_id integer not null
);

create index qdrant_id_idx ON document_segment(qdrant_id);
create index docuemnt_id_idx ON document_segment(document_id);
