CREATE TABLE document(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  doc text
);

CREATE TABLE document_segment(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fragment text,
  document_id integer not null
);

create index vector_idx ON document_segment(vector);
