server:
  port: 8080

spring:
  application:
    name: demo
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      jdbc-url: jdbc:postgresql://localhost:5432/test
#      connection-test-query: select 1
#      maximum-pool-size: 10
#      connection-timeout: 3000
#  jpa:
#    hibernate:
#      ddl-auto: none

