POST http://localhost:8080/digest/html
Content-Type: text/html

<div>Some text</div>


###

# @timeout 6000
POST http://localhost:8080/query
Content-Type: application/json

"Как проверить работоспособность сети?"

###

# @timeout 6000
POST http://localhost:8080/query/advice
Content-Type: application/json

"Как проверить открыт ли порт на удалённом сервере?"

