# @timeout 6000
POST http://localhost:8080/api/v1/chat/completions
Content-Type: text/plain

Привет!

####

# @timeout 6000
POST http://localhost:8080/api/v1/chat/completions
Content-Type: text/plain

Привет!

####